### ISSUE TITLE
gulp.spritesmith issue - unprefix removes media queries for first file

### ISSUE THREAD

**Issue by s-pyadyshev** [gucong3000/postcss-unprefix#76]
If you use postcss-unprefix with https://github.com/twolfson/gulp.spritesmith

Result:
```css
.icon-sprite1 {
  background-image: url(sprite.png);
  background-position: -100px 0px;
  width: 50px;
  height: 50px;
}
.icon-sprite2 {
  background-image: url(sprite.png);
  background-position: -100px -50px;
  width: 50px;
  height: 50px;
}

@media (-webkit-min-device-pixel-ratio: 2),
       (min-resolution: 192dpi) {
  .icon-sprite2 {
    background-image: url(sprite@2x.png);
    background-size: 150px 200px;
  }
}
```
Expected result:
```css
.icon-sprite1 {
  background-image: url(sprite.png);
  background-position: -100px 0px;
  width: 50px;
  height: 50px;
}
.icon-sprite2 {
  background-image: url(sprite.png);
  background-position: -100px -50px;
  width: 50px;
  height: 50px;
}

@media (-webkit-min-device-pixel-ratio: 2),
       (min-resolution: 192dpi) {
  .icon-sprite1 {
    background-image: url(sprite@2x.png);
    background-size: 150px 200px;
  }
  .icon-sprite2 {
    background-image: url(sprite@2x.png);
    background-size: 150px 200px;
  }
}
```

I'll provide example repo later
